In [0]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

In [3]:
url = 'https://raw.githubusercontent.com/SohelRaja/ML_repo_college/master/Decision%20Tree%20with%20Python/WA_Fn-UseC_-Telco-Customer-Churn.csv'
telco = pd.read_csv(url)
telco=telco.drop(['customerID','TotalCharges'] , axis=1)
telco.head(20)

    gender  SeniorCitizen  ... MonthlyCharges Churn
0   Female              0  ...          29.85    No
1     Male              0  ...          56.95    No
2     Male              0  ...          53.85   Yes
3     Male              0  ...          42.30    No
4   Female              0  ...          70.70   Yes
5   Female              0  ...          99.65   Yes
6     Male              0  ...          89.10    No
7   Female              0  ...          29.75    No
8   Female              0  ...         104.80   Yes
9     Male              0  ...          56.15    No
10    Male              0  ...          49.95    No
11    Male              0  ...          18.95    No
12    Male              0  ...         100.35    No
13    Male              0  ...         103.70   Yes
14    Male              0  ...         105.50    No
15  Female              0  ...         113.25    No
16  Female              0  ...          20.65    No
17    Male              0  ...         106.70    No
18  Female              0  ...          55.20   Yes
19  Female              0  ...          90.05    No

[20 rows x 19 columns]

In [4]:
telco['Partner'].replace(to_replace=[['No'],['Yes']],value=['PartnerNo','PartnerYes'],inplace=True)
telco['Dependents'].replace(to_replace=[['No'],['Yes']],value=['Independent','Dependent'],inplace=True)
telco['PhoneService'].replace(to_replace=[['No'],['Yes']],value=['PSNo','PSYes'],inplace=True)
telco['PaperlessBilling'].replace(to_replace=[['No'],['Yes']],value=['PLBNo','PLBYes'],inplace=True)
telco['MultipleLines'].replace(to_replace=[['No phone service'],['No'],['Yes']],value=['MLNo','MLNo','MLYes'],inplace=True)
telco['OnlineSecurity'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['OSNo','OSNo','OSYes'],inplace=True)
telco['OnlineBackup'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['OBNo','OBNo','OBYes'],inplace=True)
telco['DeviceProtection'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['DPNo','DPNo','DPYes'],inplace=True)
telco['TechSupport'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['TSNo','TSNo','TSYes'],inplace=True)
telco['StreamingTV'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['STVNo','STVNo','STVYes'],inplace=True)
telco['StreamingMovies'].replace(to_replace=[['No internet service'],['No'],['Yes']],value=['SMNo','SMNo','SMYes'],inplace=True)
telco.head(20)

    gender  SeniorCitizen  ... MonthlyCharges Churn
0   Female              0  ...          29.85    No
1     Male              0  ...          56.95    No
2     Male              0  ...          53.85   Yes
3     Male              0  ...          42.30    No
4   Female              0  ...          70.70   Yes
5   Female              0  ...          99.65   Yes
6     Male              0  ...          89.10    No
7   Female              0  ...          29.75    No
8   Female              0  ...         104.80   Yes
9     Male              0  ...          56.15    No
10    Male              0  ...          49.95    No
11    Male              0  ...          18.95    No
12    Male              0  ...         100.35    No
13    Male              0  ...         103.70   Yes
14    Male              0  ...         105.50    No
15  Female              0  ...         113.25    No
16  Female              0  ...          20.65    No
17    Male              0  ...         106.70    No
18  Female              0  ...          55.20   Yes
19  Female              0  ...          90.05    No

[20 rows x 19 columns]

In [5]:
telco['gender'].replace(to_replace=[['Female'],['Male']],value=[0,1],inplace=True)
telco['Partner'].replace(to_replace=[['PartnerNo'],['PartnerYes']],value=[0,1],inplace=True)
telco['Dependents'].replace(to_replace=[['Independent'],['Dependent']],value=[0,1],inplace=True)
telco['PhoneService'].replace(to_replace=[['PSNo'],['PSYes']],value=[0,1],inplace=True)
telco['PaperlessBilling'].replace(to_replace=[['PLBNo'],['PLBYes']],value=[0,1],inplace=True)
telco['MultipleLines'].replace(to_replace=[['MLNo'],['MLYes']],value=[0,1],inplace=True)
telco['OnlineSecurity'].replace(to_replace=[['OSNo'],['OSYes']],value=[0,1],inplace=True)
telco['OnlineBackup'].replace(to_replace=[['OBNo'],['OBYes']],value=[0,1],inplace=True)
telco['DeviceProtection'].replace(to_replace=[['DPNo'],['DPYes']],value=[0,1],inplace=True)
telco['TechSupport'].replace(to_replace=[['TSNo'],['TSYes']],value=[0,1],inplace=True)
telco['StreamingTV'].replace(to_replace=[['STVNo'],['STVYes']],value=[0,1],inplace=True)
telco['StreamingMovies'].replace(to_replace=[['SMNo'],['SMYes']],value=[0,1],inplace=True)
telco['InternetService'].replace(to_replace=[['DSL'],['Fiber optic'],['No']],value=[0,1,2],inplace=True)
telco['PaymentMethod'].replace(to_replace=[['Electronic check'],['Mailed check'],['Bank transfer (automatic)'],['Credit card (automatic)']],value=[0,1,2,3],inplace=True)
telco['Contract'].replace(to_replace=[['Month-to-month'], ['One year'], ['Two year']],value=[0,1,2],inplace=True)
telco['Churn'].replace(to_replace=[['No'], ['Yes']],value=[0,1],inplace=True)
telco.head(20)

    gender  SeniorCitizen  Partner  ...  PaymentMethod  MonthlyCharges  Churn
0        0              0        1  ...              0           29.85      0
1        1              0        0  ...              1           56.95      0
2        1              0        0  ...              1           53.85      1
3        1              0        0  ...              2           42.30      0
4        0              0        0  ...              0           70.70      1
5        0              0        0  ...              0           99.65      1
6        1              0        0  ...              3           89.10      0
7        0              0        0  ...              1           29.75      0
8        0              0        1  ...              0          104.80      1
9        1              0        0  ...              2           56.15      0
10       1              0        1  ...              1           49.95      0
11       1              0        0  ...              3           18.95      0
12       1              0        1  ...              3          100.35      0
13       1              0        0  ...              2          103.70      1
14       1              0        0  ...              0          105.50      0
15       0              0        1  ...              3          113.25      0
16       0              0        0  ...              1           20.65      0
17       1              0        0  ...              2          106.70      0
18       0              0        1  ...              3           55.20      1
19       0              0        0  ...              0           90.05      0

[20 rows x 19 columns]

In [6]:
telco.describe()

            gender  SeniorCitizen  ...  MonthlyCharges        Churn
count  7043.000000    7043.000000  ...     7043.000000  7043.000000
mean      0.504756       0.162147  ...       64.761692     0.265370
std       0.500013       0.368612  ...       30.090047     0.441561
min       0.000000       0.000000  ...       18.250000     0.000000
25%       0.000000       0.000000  ...       35.500000     0.000000
50%       1.000000       0.000000  ...       70.350000     0.000000
75%       1.000000       0.000000  ...       89.850000     1.000000
max       1.000000       1.000000  ...      118.750000     1.000000

[8 rows x 19 columns]

**Train Test Split**

In [7]:
X=telco[['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','MonthlyCharges']]
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
X1=telco[['tenure','InternetService','PhoneService']]
X1=scaler.fit_transform(X1)
y=telco['Churn']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=2)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)
X1_train,X1_test,y_train,y_test=train_test_split(X1,y,test_size=0.1,random_state=2)
print ('Modified Train set:', X1_train.shape,  y_train.shape)
print ('Modified Test set:', X1_test.shape,  y_test.shape)

Train set: (6338, 18) (6338,)
Test set: (705, 18) (705,)
Modified Train set: (6338, 3) (6338,)
Modified Test set: (705, 3) (705,)

**Hyper-Parameter Tuning**

In [8]:
from sklearn.metrics import f1_score
from sklearn import svm
kernels=['linear','poly','rbf','sigmoid']
cs=[0.1,1,10,100,1000]
gammas=[0.1,1,10,100]
for item in kernels:
  if (item=='rbf'):
    for c in cs:
      for g in gammas:
        clf = svm.SVC(kernel=item,C=c,gamma=g)
        clf.fit(X_train, y_train)
        y_pred=clf.predict(X_test)
        accuracy=f1_score(y_test, y_pred,average='weighted') 
        print('Kernel=',item,' C=',c,'gamma=',g,' Accuracy=',accuracy*100,"%")
  elif item=='poly':
    for degree in range(10):
      clf=svm.SVC(kernel=item,degree=degree,gamma=0.1)
      clf.fit(X_train, y_train)
      y_pred=clf.predict(X_test)
      accuracy=f1_score(y_test, y_pred,average='weighted') 
      print('Kernel=',item,'degree=',degree,'gamma=0.1','Accuracy=',accuracy*100,"%")
  else:
    clf=svm.SVC(kernel=item)
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    accuracy=f1_score(y_test, y_pred,average='weighted') 
    print('Kernel=',item,'Accuracy=',accuracy*100,"%")

Kernel= linear Accuracy= 79.79704081809825 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 0 gamma=0.1 Accuracy= 66.63729608506085 %
Kernel= poly degree= 1 gamma=0.1 Accuracy= 79.84764559307506 %
Kernel= poly degree= 2 gamma=0.1 Accuracy= 78.58622340608831 %
Kernel= poly degree= 3 gamma=0.1 Accuracy= 79.4381897215116 %
Kernel= poly degree= 4 gamma=0.1 Accuracy= 77.69689636979503 %
Kernel= poly degree= 5 gamma=0.1 Accuracy= 77.2540216580449 %
Kernel= poly degree= 6 gamma=0.1 Accuracy= 76.08378190215824 %
Kernel= poly degree= 7 gamma=0.1 Accuracy= 76.81011049736433 %
Kernel= poly degree= 8 gamma=0.1 Accuracy= 75.89656852997712 %
Kernel= poly degree= 9 gamma=0.1 Accuracy= 76.29418544965634 %
Kernel= rbf  C= 0.1 gamma= 0.1  Accuracy= 78.08461876046357 %
Kernel= rbf  C= 0.1 gamma= 1  Accuracy= 66.90132768880818 %
Kernel= rbf  C= 0.1 gamma= 10  Accuracy= 66.90132768880818 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= rbf  C= 0.1 gamma= 100  Accuracy= 66.63729608506085 %
Kernel= rbf  C= 1 gamma= 0.1  Accuracy= 80.367519127974 %
Kernel= rbf  C= 1 gamma= 1  Accuracy= 75.08206926817022 %
Kernel= rbf  C= 1 gamma= 10  Accuracy= 73.5450795765595 %
Kernel= rbf  C= 1 gamma= 100  Accuracy= 72.7155540263005 %
Kernel= rbf  C= 10 gamma= 0.1  Accuracy= 77.68208110537917 %
Kernel= rbf  C= 10 gamma= 1  Accuracy= 73.67596836012666 %
Kernel= rbf  C= 10 gamma= 10  Accuracy= 74.39628815347106 %
Kernel= rbf  C= 10 gamma= 100  Accuracy= 73.60348430005004 %
Kernel= rbf  C= 100 gamma= 0.1  Accuracy= 77.2540216580449 %
Kernel= rbf  C= 100 gamma= 1  Accuracy= 73.24078733731764 %
Kernel= rbf  C= 100 gamma= 10  Accuracy= 74.50303721156668 %
Kernel= rbf  C= 100 gamma= 100  Accuracy= 73.85433987971423 %
Kernel= rbf  C= 1000 gamma= 0.1  Accuracy= 74.05618316272687 %
Kernel= rbf  C= 1000 gamma= 1  Accuracy= 73.85375360981156 %
Kernel= rbf  C= 1000 gamma= 10  Accuracy= 74.50303721156668 %
Kernel= rbf  C= 1000 gamma= 100  Accuracy= 73.68829228103407 %

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Kernel= sigmoid Accuracy= 75.26620911686209 %

In [9]:
for item in kernels:
  if (item=='rbf'):
    for c in cs:
      for g in gammas:
        clf = svm.SVC(kernel=item,C=c,gamma=g)
        clf.fit(X1_train, y_train)
        y_pred=clf.predict(X1_test)
        accuracy=f1_score(y_test, y_pred,average='weighted') 
        print('Kernel=',item,' C=',c,'gamma=',g,' Accuracy=',accuracy*100,"%")
  elif item=='poly':
    for degree in range(10):
      clf=svm.SVC(kernel=item,degree=degree,gamma=0.1)
      clf.fit(X1_train, y_train)
      y_pred=clf.predict(X1_test)
      accuracy=f1_score(y_test, y_pred,average='weighted') 
      print('Kernel=',item,'degree=',degree,'gamma=0.1','Accuracy=',accuracy*100,"%")
  else:
    clf=svm.SVC(kernel=item)
    clf.fit(X1_train, y_train)
    y_pred=clf.predict(X1_test)
    accuracy=f1_score(y_test, y_pred,average='weighted') 
    print('Kernel=',item,'Accuracy=',accuracy*100,"%")

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= linear Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 0 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 1 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 2 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 3 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 4 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 5 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 6 gamma=0.1 Accuracy= 66.63729608506085 %

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Kernel= poly degree= 7 gamma=0.1 Accuracy= 66.63729608506085 %
Kernel= poly degree= 8 gamma=0.1 Accuracy= 69.20765614667447 %
Kernel= poly degree= 9 gamma=0.1 Accuracy= 69.20765614667447 %
Kernel= rbf  C= 0.1 gamma= 0.1  Accuracy= 79.51923344840492 %
Kernel= rbf  C= 0.1 gamma= 1  Accuracy= 79.62281338390692 %
Kernel= rbf  C= 0.1 gamma= 10  Accuracy= 80.42168997128074 %
Kernel= rbf  C= 0.1 gamma= 100  Accuracy= 80.23566110168416 %
Kernel= rbf  C= 1 gamma= 0.1  Accuracy= 79.40047060164063 %
Kernel= rbf  C= 1 gamma= 1  Accuracy= 80.73290850331426 %
Kernel= rbf  C= 1 gamma= 10  Accuracy= 80.5498969154021 %
Kernel= rbf  C= 1 gamma= 100  Accuracy= 80.42168997128074 %
Kernel= rbf  C= 10 gamma= 0.1  Accuracy= 79.17461189930748 %
Kernel= rbf  C= 10 gamma= 1  Accuracy= 80.7922546300313 %
Kernel= rbf  C= 10 gamma= 10  Accuracy= 80.42168997128074 %
Kernel= rbf  C= 10 gamma= 100  Accuracy= 79.86110216678892 %
Kernel= rbf  C= 100 gamma= 0.1  Accuracy= 79.17461189930748 %
Kernel= rbf  C= 100 gamma= 1  Accuracy= 80.73290850331426 %
Kernel= rbf  C= 100 gamma= 10  Accuracy= 80.06169559499769 %
Kernel= rbf  C= 100 gamma= 100  Accuracy= 80.12607097585959 %
Kernel= rbf  C= 1000 gamma= 0.1  Accuracy= 80.66498095936834 %
Kernel= rbf  C= 1000 gamma= 1  Accuracy= 80.5498969154021 %
Kernel= rbf  C= 1000 gamma= 10  Accuracy= 80.42168997128074 %
Kernel= rbf  C= 1000 gamma= 100  Accuracy= 80.12607097585959 %

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

Kernel= sigmoid Accuracy= 61.105635448308085 %

**Best Accuracy**

In [10]:

from sklearn.metrics import classification_report
clf = svm.SVC(kernel='rbf',C=1,gamma=0.1)
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88       541
           1       0.63      0.48      0.54       164

    accuracy                           0.81       705
   macro avg       0.74      0.70      0.71       705
weighted avg       0.80      0.81      0.80       705

In [11]:
clf = svm.SVC(kernel='rbf',C=10,gamma=1)
clf.fit(X1_train, y_train)
y_pred1=clf.predict(X1_test)
print (classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.85      0.92      0.89       541
           1       0.65      0.48      0.55       164

    accuracy                           0.82       705
   macro avg       0.75      0.70      0.72       705
weighted avg       0.81      0.82      0.81       705